#!/bin/bash

OUTPUT_DIR="OpenGPWS"
case $(uname) in
Darwin)
	INSTALL="install -m 644"
	;;
*)
	INSTALL="install -D -m 644"
	;;
esac

while getopts "G" o; do
	case "${o}" in
	G)
		GARMIN=1
		;;
	esac
done

if ! opusenc -h &> /dev/null ; then
	echo "Couldn't find \"opusenc\" command. Please install \"opus-tools\"" \
	    >&2
	exit 1
fi

set -e

rm -rf "$OUTPUT_DIR" "$OUTPUT_DIR.zip"
mkdir -p "$OUTPUT_DIR"

( cd qmake && ./build ) || exit 1

if [[ $(uname) = "Linux" ]]; then
	$INSTALL -- "qmake/output/lin_x64/${OUTPUT_DIR}.xpl" \
	    "$OUTPUT_DIR/lin_x64/${OUTPUT_DIR}.xpl"
	$INSTALL -- "qmake/output/win_x64/${OUTPUT_DIR}.xpl" \
	    "$OUTPUT_DIR/win_x64/${OUTPUT_DIR}.xpl"
	$INSTALL -- "qmake/output/win_x64/syms.txt" \
	    "$OUTPUT_DIR/win_x64/syms.txt"
else
	# MacOS "install" is such a pile of trash that it can't create
	# directories automatically while copying files, so we need to
	# hold its hand and do it manually.
	mkdir -p "$OUTPUT_DIR/mac_x64" \
	    "$OUTPUT_DIR/data/garmin" \
	    "$OUTPUT_DIR/data/ra/garmin" \
	    "$OUTPUT_DIR/data/ra/boeing" \
	    "$OUTPUT_DIR/opengpws"
	$INSTALL -- "qmake/output/mac_x64/${OUTPUT_DIR}.xpl" \
	    "$OUTPUT_DIR/mac_x64/${OUTPUT_DIR}.xpl"
fi

find data -iname '*.flac' | fgrep -v '/src/' | while read; do
	if ! [ -f "${REPLY/%.flac/.opus}" ]; then
		opusenc --bitrate 32 "${REPLY}" "${REPLY/%.flac/.opus}"
	fi
done

if [ -z "$GARMIN" ]; then
	find data -iname '*.opus' -or -iname '*.vert' -or -iname '*.frag' | \
	    while read; do
		$INSTALL -- "$REPLY" "$OUTPUT_DIR/$REPLY"
	done
else
	find data -iname '*.vert' -or -iname '*.frag' | while read; do
		$INSTALL -- "$REPLY" "$OUTPUT_DIR/$REPLY"
	done
	for FILE in data/*.opus; do
		$INSTALL -- "$FILE" "$OUTPUT_DIR/$FILE"
	done
	find data/ra -iname '*.opus' | while read; do
		$INSTALL -- "$REPLY" "$OUTPUT_DIR/$REPLY"
	done
	find data/garmin -iname '*.opus' | while read; do
		$INSTALL -- "$REPLY" "$OUTPUT_DIR/data"
	done
fi

$INSTALL -- "api/opengpws/xplane_api.h" "$OUTPUT_DIR/opengpws/xplane_api.h"

# ZIP up the product
zip -r "$OUTPUT_DIR.zip" "$OUTPUT_DIR"
